apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: vpod.kb.io
  namespaceSelector:
    matchLabels:
      cosigned: "true"