apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- name: cosigned.sigstore.dev
  namespaceSelector:
    matchLabels:
      cosigned: "true"