# permissions for end users to edit policies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: policy-editor-role
rules:
- apiGroups:
  - cosigned.sigstore.dev
  resources:
  - policies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cosigned.sigstore.dev
  resources:
  - policies/status
  verbs:
  - get
