---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["list", "get", "watch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["list", "get", "watch", "create"]
- apiGroups: ["coordination.k8s.io"]
  resources:
  - leases
  verbs: ["list", "get", "watch", "create", "update", "delete"]